print('MÉTODO 1 --------------')
n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))
soma = n1 + n2
print(f'A soma de {n1} e {n2} é {soma}.')
print('-----------------------')
print('MÉTODO 2 --------------')
n1 = input('Digite um número: ')
n2 = input('Digite outro número: ')
soma = int(n1) + int(n2)
print('A soma de {} e {} é {}.'.format(n1, n2,soma))
